[build]
  publish = "/"  # Ou qualquer diretório correto onde o index.html está localizado
  functions = "netlify/functions"  # Mantém o diretório de funções como está

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/block-html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; img-src 'none'; script-src 'none'; style-src 'none';"
    Referrer-Policy = "no-referrer"
