[build]
  publish = "public"              # A pasta onde os arquivos estáticos estão
  functions = "netlify/functions" # A pasta onde as funções estão

[[redirects]]
  from = "/*"                     # Redireciona todas as requisições
  to = "/.netlify/functions/block-html" # Para a função que bloqueia o index.html
  status = 200
  force = true                    # Força o redirecionamento